/* generated by Makefile.devel from version.sh */
#define PACKAGE_NAME "GNU CLISP"
#define PACKAGE_TARNAME "clisp"
#define PACKAGE_VERSION "2.49.51 (2017-04-17)"
#define PACKAGE_STRING "GNU CLISP 2.49.51 (2017-04-17)"
#define PACKAGE_BUGREPORT "http://clisp.org/"
